Repository alimitedgroup/alimitedgroup.github.io, pull requests merged in 2025-04, with the labels that each got.

#221 Specifica Tecnica: aggiungere informazioni su router e main
  03-PB/documenti-esterni/specifica-tecnica.typ
  assets/catalog/CatalogRouter.png
  assets/order/OrderInfo.png
  assets/order/SendOrderUpdateCmd.png
  assets/order/SendTransferUpdateCmd.png
  assets/order/TransferInfo.png
  assets/warehouse/StockUpdateGood.png
Labels: documentazione - redazione

#240 Quick Fix MU
  .github/workflows/glossary.py
  03-PB/manuale-utente/concetti/merci.md
  03-PB/manuale-utente/concetti/ordini.md
  03-PB/manuale-utente/concetti/riassortimenti.md
  03-PB/manuale-utente/concetti/tipi-utenti.md
  03-PB/manuale-utente/concetti/trasferimenti.md
  03-PB/manuale-utente/guide/aggiunta-stock.md
  03-PB/manuale-utente/guide/ordine.md
  03-PB/manuale-utente/guide/rimozione-stock.md
  03-PB/manuale-utente/guide/trasferimento.md
  03-PB/manuale-utente/installazione/preparazione-del-sistema/01-installazione-sw.md
  03-PB/manuale-utente/operazione/Test.md
  03-PB/manuale-utente/telemetria/config.md
  03-PB/manuale-utente/telemetria/dashboard.md
Labels: documentazione - redazione, sito

#239 215 piano di progetto aggiornare la pianificazione a lungo termine
  03-PB/documenti-esterni/piano-di-progetto.typ
Labels: documentazione - verifica

#247 Approvazione esterna VE 04-04
  03-PB/documenti-esterni/verbali/2025-02-28.typ
  03-PB/documenti-esterni/verbali/2025-03-25.typ
  03-PB/documenti-esterni/verbali/2025-04-04.typ
  assets/firma_ve0404.png
  assets/firma_ve2503.png
Labels: documentazione - approvazione
