Repository alimitedgroup/alimitedgroup.github.io, pull requests merged in 2025-02, with the labels that each got.

#121 117 redazione piano di progetto per il sesto sprint
  02-RTB/documenti-esterni/piano-di-progetto.typ
  lib/common.typ
  lib/pdp.typ
Labels: documentazione - redazione

#153 Correzione UC67-UC68
  02-RTB/documenti-esterni/analisi-requisiti.typ
  03-PB/documenti-esterni/analisi-requisiti.typ
  03-PB/documenti-esterni/piano-di-qualifica.typ
  assets/diagrams/UC67-old.png
  assets/diagrams/UC67.png
  assets/diagrams/UC68-old.png
  assets/diagrams/UC68.png
  assets/diagrams/attori-old.png
  assets/diagrams/attori.drawio
  assets/diagrams/attori.png
Labels: documentazione - verifica

#150 141 redazione specifica tecnica
  03-PB/documenti-esterni/specifica-tecnica.typ
  lib/importantdocs.typ
Labels: documentazione - redazione

#148 Inizio del manuale utente
  .github/workflows/push.yml
  03-PB/documenti-esterni/manuale-utente.typ
  03-PB/manuale-utente/01-getting-started/index.md
  03-PB/manuale-utente/02-guides/index.md
  03-PB/manuale-utente/02-guides/registrazione.md
  03-PB/manuale-utente/assets/altd.png
  03-PB/manuale-utente/index.md
  lib/importantdocs.typ
  mkdocs.yml
  pyproject.toml
  uv.lock
  website/index.html
Labels: sito
